package com.yjt.basketball.service;

import org.springframework.stereotype.Service;

import java.util.Map;

@Service
public class DisplayNameService {

    private static final String[] FALLBACK_POSITIONS = {"PG", "SG", "SF", "PF", "C"};

    private static final Map<String, String> TEAM_CN = Map.ofEntries(
            Map.entry("Atlanta Hawks", "老鹰"),
            Map.entry("Brooklyn Nets", "篮网"),
            Map.entry("Boston Celtics", "凯尔特人"),
            Map.entry("Charlotte Hornets", "黄蜂"),
            Map.entry("Chicago Bulls", "公牛"),
            Map.entry("Cleveland Cavaliers", "骑士"),
            Map.entry("Dallas Mavericks", "独行侠"),
            Map.entry("Denver Nuggets", "掘金"),
            Map.entry("Detroit Pistons", "活塞"),
            Map.entry("Golden State Warriors", "勇士"),
            Map.entry("Houston Rockets", "火箭"),
            Map.entry("Indiana Pacers", "步行者"),
            Map.entry("LA Clippers", "快船"),
            Map.entry("Los Angeles Clippers", "快船"),
            Map.entry("Los Angeles Lakers", "湖人"),
            Map.entry("LA Lakers", "湖人"),
            Map.entry("Memphis Grizzlies", "灰熊"),
            Map.entry("Miami Heat", "热火"),
            Map.entry("Milwaukee Bucks", "雄鹿"),
            Map.entry("Minnesota Timberwolves", "森林狼"),
            Map.entry("New Orleans Pelicans", "鹈鹕"),
            Map.entry("New York Knicks", "尼克斯"),
            Map.entry("Oklahoma City Thunder", "雷霆"),
            Map.entry("Orlando Magic", "魔术"),
            Map.entry("Philadelphia 76ers", "76人"),
            Map.entry("Phoenix Suns", "太阳"),
            Map.entry("Portland Trail Blazers", "开拓者"),
            Map.entry("Sacramento Kings", "国王"),
            Map.entry("San Antonio Spurs", "马刺"),
            Map.entry("Toronto Raptors", "猛龙"),
            Map.entry("Utah Jazz", "爵士"),
            Map.entry("Washington Wizards", "奇才")
    );

    private static final Map<String, String> TEAM_ABBR = Map.ofEntries(
            Map.entry("Atlanta Hawks", "ATL"),
            Map.entry("Brooklyn Nets", "BKN"),
            Map.entry("Boston Celtics", "BOS"),
            Map.entry("Charlotte Hornets", "CHA"),
            Map.entry("Chicago Bulls", "CHI"),
            Map.entry("Cleveland Cavaliers", "CLE"),
            Map.entry("Dallas Mavericks", "DAL"),
            Map.entry("Denver Nuggets", "DEN"),
            Map.entry("Detroit Pistons", "DET"),
            Map.entry("Golden State Warriors", "GSW"),
            Map.entry("Houston Rockets", "HOU"),
            Map.entry("Indiana Pacers", "IND"),
            Map.entry("LA Clippers", "LAC"),
            Map.entry("Los Angeles Clippers", "LAC"),
            Map.entry("Los Angeles Lakers", "LAL"),
            Map.entry("LA Lakers", "LAL"),
            Map.entry("Memphis Grizzlies", "MEM"),
            Map.entry("Miami Heat", "MIA"),
            Map.entry("Milwaukee Bucks", "MIL"),
            Map.entry("Minnesota Timberwolves", "MIN"),
            Map.entry("New Orleans Pelicans", "NOP"),
            Map.entry("New York Knicks", "NYK"),
            Map.entry("Oklahoma City Thunder", "OKC"),
            Map.entry("Orlando Magic", "ORL"),
            Map.entry("Philadelphia 76ers", "PHI"),
            Map.entry("Phoenix Suns", "PHX"),
            Map.entry("Portland Trail Blazers", "POR"),
            Map.entry("Sacramento Kings", "SAC"),
            Map.entry("San Antonio Spurs", "SAS"),
            Map.entry("Toronto Raptors", "TOR"),
            Map.entry("Utah Jazz", "UTA"),
            Map.entry("Washington Wizards", "WAS")
    );

    private static final Map<String, String> PLAYER_CN = Map.ofEntries(
            Map.entry("Shai Gilgeous-Alexander", "亚历山大"),
            Map.entry("Jalen Williams", "杰伦·威廉姆斯"),
            Map.entry("Jaylin Williams", "杰林·威廉姆斯"),
            Map.entry("Chet Holmgren", "霍姆格伦"),
            Map.entry("Alex Caruso", "卡鲁索"),
            Map.entry("Cason Wallace", "卡森·华莱士"),
            Map.entry("Luguentz Dort", "多尔特"),
            Map.entry("Isaiah Hartenstein", "哈尔滕施泰因"),
            Map.entry("Aaron Wiggins", "阿龙·威金斯"),
            Map.entry("Ajay Mitchell", "阿杰·米切尔"),
            Map.entry("Isaiah Joe", "以赛亚·乔"),
            Map.entry("Kenrich Williams", "肯里奇·威廉姆斯"),
            Map.entry("Bennedict Mathurin", "本尼迪克特·马瑟林"),
            Map.entry("Pascal Siakam", "西亚卡姆"),
            Map.entry("T.J. McConnell", "T.J. 麦康奈尔"),
            Map.entry("Andrew Nembhard", "安德鲁·内姆布哈德"),
            Map.entry("Tyrese Haliburton", "哈利伯顿"),
            Map.entry("Myles Turner", "迈尔斯·特纳"),
            Map.entry("Aaron Nesmith", "阿龙·内史密斯"),
            Map.entry("Tony Bradley", "托尼·布拉德利"),
            Map.entry("Obi Toppin", "奥比·托平"),
            Map.entry("Ben Sheppard", "本·谢泼德"),
            Map.entry("Jarace Walker", "贾拉斯·沃克"),
            Map.entry("Thomas Bryant", "托马斯·布莱恩特"),
            Map.entry("Jayson Tatum", "塔图姆"),
            Map.entry("Jaylen Brown", "杰伦·布朗"),
            Map.entry("Derrick White", "德里克·怀特"),
            Map.entry("Jrue Holiday", "朱·霍勒迪"),
            Map.entry("Al Horford", "艾尔·霍福德"),
            Map.entry("Baylor Scheierman", "贝勒·谢尔曼"),
            Map.entry("JD Davison", "JD·戴维森"),
            Map.entry("Jordan Walsh", "乔丹·沃尔什"),
            Map.entry("Kristaps Porzingis", "波尔津吉斯"),
            Map.entry("Kristaps Porziņģis", "波尔津吉斯"),
            Map.entry("Payton Pritchard", "普理查德"),
            Map.entry("Sam Hauser", "萨姆·豪瑟"),
            Map.entry("Luke Kornet", "卢克·科内特"),
            Map.entry("Neemias Queta", "尼米亚斯·克塔"),
            Map.entry("Torrey Craig", "托里·克雷格"),
            Map.entry("Xavier Tillman", "泽维尔·蒂尔曼"),
            Map.entry("Nikola Jokic", "约基奇"),
            Map.entry("Nikola Jokić", "约基奇"),
            Map.entry("Jamal Murray", "贾马尔·穆雷"),
            Map.entry("Aaron Gordon", "阿龙·戈登"),
            Map.entry("Michael Porter Jr.", "小迈克尔·波特"),
            Map.entry("Russell Westbrook", "威斯布鲁克"),
            Map.entry("Christian Braun", "克里斯蒂安·布劳恩"),
            Map.entry("DeAndre Jordan", "小乔丹"),
            Map.entry("Peyton Watson", "佩顿·沃特森"),
            Map.entry("Anthony Edwards", "爱德华兹"),
            Map.entry("Karl-Anthony Towns", "唐斯"),
            Map.entry("Rudy Gobert", "戈贝尔"),
            Map.entry("Mike Conley", "迈克·康利"),
            Map.entry("Jaden McDaniels", "杰登·麦克丹尼尔斯"),
            Map.entry("Naz Reid", "纳兹·里德"),
            Map.entry("Nickeil Alexander-Walker", "尼基尔·亚历山大-沃克"),
            Map.entry("Stephen Curry", "库里"),
            Map.entry("Jimmy Butler", "吉米·巴特勒"),
            Map.entry("Jimmy Butler III", "吉米·巴特勒"),
            Map.entry("Draymond Green", "德雷蒙德·格林"),
            Map.entry("Jonathan Kuminga", "库明加"),
            Map.entry("Buddy Hield", "巴迪·希尔德"),
            Map.entry("Brandin Podziemski", "波杰姆斯基"),
            Map.entry("Moses Moody", "穆迪"),
            Map.entry("Gary Payton II", "加里·佩顿二世"),
            Map.entry("Kevon Looney", "卢尼"),
            Map.entry("LeBron James", "詹姆斯"),
            Map.entry("Anthony Davis", "安东尼·戴维斯"),
            Map.entry("Luka Doncic", "东契奇"),
            Map.entry("Luka Dončić", "东契奇"),
            Map.entry("Austin Reaves", "里夫斯"),
            Map.entry("Rui Hachimura", "八村塁"),
            Map.entry("Gabe Vincent", "文森特"),
            Map.entry("Dorian Finney-Smith", "芬尼-史密斯"),
            Map.entry("Kevin Durant", "杜兰特"),
            Map.entry("Devin Booker", "布克"),
            Map.entry("Bradley Beal", "比尔"),
            Map.entry("Kyrie Irving", "欧文"),
            Map.entry("Klay Thompson", "克莱·汤普森"),
            Map.entry("Giannis Antetokounmpo", "字母哥"),
            Map.entry("Damian Lillard", "利拉德"),
            Map.entry("Donovan Mitchell", "米切尔"),
            Map.entry("Jalen Brunson", "布伦森"),
            Map.entry("Joel Embiid", "恩比德"),
            Map.entry("Paolo Banchero", "班凯罗"),
            Map.entry("James Harden", "哈登"),
            Map.entry("Kawhi Leonard", "莱昂纳德"),
            Map.entry("Paul George", "保罗·乔治"),
            Map.entry("Ja Morant", "莫兰特"),
            Map.entry("Bam Adebayo", "阿德巴约"),
            Map.entry("Tyler Herro", "希罗"),
            Map.entry("Cade Cunningham", "坎宁安"),
            Map.entry("Tobias Harris", "托拜厄斯·哈里斯"),
            Map.entry("Malik Beasley", "马利克·比斯利")
    );

    private static final Map<String, String> NAME_PART_CN = Map.ofEntries(
            Map.entry("AJ", "AJ"),
            Map.entry("Aaron", "阿龙"),
            Map.entry("Achiuwa", "阿丘瓦"),
            Map.entry("Adams", "亚当斯"),
            Map.entry("Adebayo", "阿德巴约"),
            Map.entry("Ajay", "阿杰"),
            Map.entry("Al", "艾尔"),
            Map.entry("Aldama", "阿尔达马"),
            Map.entry("Alec", "亚历克"),
            Map.entry("Alexander", "亚历山大"),
            Map.entry("Alex", "亚历克斯"),
            Map.entry("Allen", "阿伦"),
            Map.entry("Alperen", "阿尔佩伦"),
            Map.entry("Amen", "阿门"),
            Map.entry("Andre", "安德烈"),
            Map.entry("Andrew", "安德鲁"),
            Map.entry("Anthony", "安东尼"),
            Map.entry("Anunoby", "阿努诺比"),
            Map.entry("Ariel", "阿里尔"),
            Map.entry("Austin", "奥斯汀"),
            Map.entry("Ausar", "奥萨尔"),
            Map.entry("Bagley", "巴格利"),
            Map.entry("Bam", "巴姆"),
            Map.entry("Bane", "贝恩"),
            Map.entry("Banchero", "班凯罗"),
            Map.entry("Batum", "巴图姆"),
            Map.entry("Baylor", "贝勒"),
            Map.entry("Beal", "比尔"),
            Map.entry("Beasley", "比斯利"),
            Map.entry("Ben", "本"),
            Map.entry("Bennedict", "本尼迪克特"),
            Map.entry("Bitadze", "比塔泽"),
            Map.entry("Black", "布莱克"),
            Map.entry("Bobby", "博比"),
            Map.entry("Bogdan", "博格丹"),
            Map.entry("Bogdanović", "博格达诺维奇"),
            Map.entry("Booker", "布克"),
            Map.entry("Bradley", "布拉德利"),
            Map.entry("Brandin", "布兰丁"),
            Map.entry("Braun", "布劳恩"),
            Map.entry("Braxton", "布拉克斯顿"),
            Map.entry("Bridges", "布里奇斯"),
            Map.entry("Brunson", "布伦森"),
            Map.entry("Bronny", "布朗尼"),
            Map.entry("Brook", "布鲁克"),
            Map.entry("Brooks", "布鲁克斯"),
            Map.entry("Brown", "布朗"),
            Map.entry("Bryant", "布莱恩特"),
            Map.entry("Buddy", "巴迪"),
            Map.entry("Burks", "伯克斯"),
            Map.entry("Butler", "巴特勒"),
            Map.entry("Cade", "凯德"),
            Map.entry("Caleb", "凯莱布"),
            Map.entry("Caldwell", "考德威尔"),
            Map.entry("Cam", "卡姆"),
            Map.entry("Cameron", "卡梅伦"),
            Map.entry("Caruso", "卡鲁索"),
            Map.entry("Carter", "卡特"),
            Map.entry("Cason", "卡森"),
            Map.entry("Čančar", "钱查尔"),
            Map.entry("Chet", "切特"),
            Map.entry("Christie", "克里斯蒂"),
            Map.entry("Christian", "克里斯蒂安"),
            Map.entry("Chris", "克里斯"),
            Map.entry("Chuma", "丘马"),
            Map.entry("Clark", "克拉克"),
            Map.entry("Cole", "科尔"),
            Map.entry("Conley", "康利"),
            Map.entry("Connaughton", "康诺顿"),
            Map.entry("Cory", "科里"),
            Map.entry("Craig", "克雷格"),
            Map.entry("Cunningham", "坎宁安"),
            Map.entry("Dadiet", "达迪耶"),
            Map.entry("Dalton", "道尔顿"),
            Map.entry("Damian", "达米安"),
            Map.entry("Darius", "达里厄斯"),
            Map.entry("Davion", "戴维恩"),
            Map.entry("Davis", "戴维斯"),
            Map.entry("Dawson", "道森"),
            Map.entry("da", "达"),
            Map.entry("De'Andre", "德安德烈"),
            Map.entry("DeAndre", "德安德烈"),
            Map.entry("Dean", "迪恩"),
            Map.entry("Delon", "德隆"),
            Map.entry("Dennis", "丹尼斯"),
            Map.entry("Derrick", "德里克"),
            Map.entry("Desmond", "德斯蒙德"),
            Map.entry("Devin", "德文"),
            Map.entry("Dieng", "迪昂"),
            Map.entry("DiVincenzo", "迪温琴佐"),
            Map.entry("Dillingham", "迪林厄姆"),
            Map.entry("Dillon", "狄龙"),
            Map.entry("Doncic", "东契奇"),
            Map.entry("Dončić", "东契奇"),
            Map.entry("Donovan", "多诺万"),
            Map.entry("Donte", "丹特"),
            Map.entry("Dorian", "多里安"),
            Map.entry("Dort", "多尔特"),
            Map.entry("Draymond", "德雷蒙德"),
            Map.entry("Drew", "德鲁"),
            Map.entry("Duncan", "邓肯"),
            Map.entry("Duren", "杜伦"),
            Map.entry("Eason", "伊森"),
            Map.entry("Edey", "埃迪"),
            Map.entry("Edwards", "爱德华兹"),
            Map.entry("Embiid", "恩比德"),
            Map.entry("Eubanks", "尤班克斯"),
            Map.entry("Evan", "埃文"),
            Map.entry("Finney", "芬尼"),
            Map.entry("Franz", "弗朗茨"),
            Map.entry("Fred", "弗雷德"),
            Map.entry("Furphy", "弗菲"),
            Map.entry("Garland", "加兰"),
            Map.entry("Garza", "加尔扎"),
            Map.entry("Gary", "加里"),
            Map.entry("Giannis", "扬尼斯"),
            Map.entry("Gobert", "戈贝尔"),
            Map.entry("Goga", "戈加"),
            Map.entry("Goodwin", "古德温"),
            Map.entry("Gordon", "戈登"),
            Map.entry("Green", "格林"),
            Map.entry("Gui", "吉"),
            Map.entry("Hachimura", "八村塁"),
            Map.entry("Haliburton", "哈利伯顿"),
            Map.entry("Harden", "哈登"),
            Map.entry("Harris", "哈里斯"),
            Map.entry("Hartenstein", "哈尔滕施泰因"),
            Map.entry("Hart", "哈特"),
            Map.entry("Hauser", "豪瑟"),
            Map.entry("Hayes", "海斯"),
            Map.entry("Haywood", "海伍德"),
            Map.entry("Herro", "希罗"),
            Map.entry("Hield", "希尔德"),
            Map.entry("Highsmith", "海史密斯"),
            Map.entry("Holiday", "霍勒迪"),
            Map.entry("Holland", "霍兰德"),
            Map.entry("Holmgren", "霍姆格伦"),
            Map.entry("Horford", "霍福德"),
            Map.entry("Houstan", "休斯坦"),
            Map.entry("Howard", "霍华德"),
            Map.entry("Huff", "赫夫"),
            Map.entry("Hukporti", "胡克波尔蒂"),
            Map.entry("Hunter", "亨特"),
            Map.entry("Isaac", "艾萨克"),
            Map.entry("Isaiah", "以赛亚"),
            Map.entry("Ivica", "伊维察"),
            Map.entry("Ja", "贾"),
            Map.entry("Jabari", "贾巴里"),
            Map.entry("Jackson", "杰克逊"),
            Map.entry("Jaden", "杰登"),
            Map.entry("Jaime", "海梅"),
            Map.entry("Jalen", "杰伦"),
            Map.entry("Jamal", "贾马尔"),
            Map.entry("James", "詹姆斯"),
            Map.entry("Jarace", "贾拉斯"),
            Map.entry("Jaren", "小贾伦"),
            Map.entry("Jarred", "贾里德"),
            Map.entry("Jarrett", "贾勒特"),
            Map.entry("Javonte", "贾文特"),
            Map.entry("Jaxson", "贾克森"),
            Map.entry("Jay", "杰"),
            Map.entry("Jaylen", "杰伦"),
            Map.entry("Jaylin", "杰林"),
            Map.entry("Jaylon", "杰伦"),
            Map.entry("Jayson", "杰森"),
            Map.entry("JD", "JD"),
            Map.entry("Jeff", "杰夫"),
            Map.entry("Jericho", "杰里科"),
            Map.entry("Jett", "杰特"),
            Map.entry("Jimmy", "吉米"),
            Map.entry("Jock", "乔克"),
            Map.entry("John", "约翰"),
            Map.entry("Johnny", "约翰尼"),
            Map.entry("Johnson", "约翰逊"),
            Map.entry("Jones", "琼斯"),
            Map.entry("Jordan", "乔丹"),
            Map.entry("Joseph", "约瑟夫"),
            Map.entry("Jović", "约维奇"),
            Map.entry("Jokić", "约基奇"),
            Map.entry("Jokic", "约基奇"),
            Map.entry("Josh", "约什"),
            Map.entry("Jrue", "朱"),
            Map.entry("Julian", "朱利安"),
            Map.entry("Julius", "朱利叶斯"),
            Map.entry("Karl", "卡尔"),
            Map.entry("Kawhi", "科怀"),
            Map.entry("Kel'el", "凯莱尔"),
            Map.entry("Kennard", "肯纳德"),
            Map.entry("Kenrich", "肯里奇"),
            Map.entry("Kentavious", "肯塔维厄斯"),
            Map.entry("Keshad", "克沙德"),
            Map.entry("Kevin", "凯文"),
            Map.entry("Kevon", "凯文"),
            Map.entry("Key", "基"),
            Map.entry("Kleber", "克勒贝尔"),
            Map.entry("Knecht", "克内克特"),
            Map.entry("Knox", "诺克斯"),
            Map.entry("Kobe", "科比"),
            Map.entry("Kolek", "科勒克"),
            Map.entry("Konchar", "康查尔"),
            Map.entry("Kornet", "科内特"),
            Map.entry("Kris", "克里斯"),
            Map.entry("Kristaps", "克里斯塔普斯"),
            Map.entry("Kuminga", "库明加"),
            Map.entry("Kuzma", "库兹马"),
            Map.entry("Kyle", "凯尔"),
            Map.entry("Lamar", "拉马尔"),
            Map.entry("Landale", "兰代尔"),
            Map.entry("Landry", "兰德里"),
            Map.entry("Larsson", "拉尔森"),
            Map.entry("LeBron", "勒布朗"),
            Map.entry("Len", "莱恩"),
            Map.entry("Leonard", "莱昂纳德"),
            Map.entry("Lillard", "利拉德"),
            Map.entry("Livingston", "利文斯顿"),
            Map.entry("Looney", "卢尼"),
            Map.entry("Lopez", "洛佩兹"),
            Map.entry("Luguentz", "吕冈茨"),
            Map.entry("Luka", "卢卡"),
            Map.entry("Luke", "卢克"),
            Map.entry("Malik", "马利克"),
            Map.entry("Marvin", "马文"),
            Map.entry("Mathurin", "马瑟林"),
            Map.entry("Max", "马克斯"),
            Map.entry("Maxi", "马克西"),
            Map.entry("McBride", "麦克布莱德"),
            Map.entry("McConnell", "麦康奈尔"),
            Map.entry("McDaniels", "麦克丹尼尔斯"),
            Map.entry("Merrill", "梅里尔"),
            Map.entry("Michael", "迈克尔"),
            Map.entry("Mikal", "米卡尔"),
            Map.entry("Mike", "迈克"),
            Map.entry("Miles", "迈尔斯"),
            Map.entry("Miller", "米勒"),
            Map.entry("Mills", "米尔斯"),
            Map.entry("Milton", "米尔顿"),
            Map.entry("Mitchell", "米切尔"),
            Map.entry("Mobley", "莫布利"),
            Map.entry("Moody", "穆迪"),
            Map.entry("Morant", "莫兰特"),
            Map.entry("Moses", "摩西"),
            Map.entry("Murray", "穆雷"),
            Map.entry("Myles", "迈尔斯"),
            Map.entry("Nate", "内特"),
            Map.entry("Naz", "纳兹"),
            Map.entry("Neemias", "尼米亚斯"),
            Map.entry("Nembhard", "内姆布哈德"),
            Map.entry("Nesmith", "内史密斯"),
            Map.entry("Nickeil", "尼基尔"),
            Map.entry("Nicolas", "尼古拉斯"),
            Map.entry("Nikola", "尼古拉"),
            Map.entry("Nnaji", "纳吉"),
            Map.entry("Norman", "诺曼"),
            Map.entry("Obi", "奥比"),
            Map.entry("OG", "OG"),
            Map.entry("Okeke", "奥科科"),
            Map.entry("Okoro", "奥科罗"),
            Map.entry("Ousmane", "乌斯曼"),
            Map.entry("Pacôme", "帕科姆"),
            Map.entry("Paolo", "保罗"),
            Map.entry("Pascal", "帕斯卡尔"),
            Map.entry("Pat", "帕特"),
            Map.entry("Patty", "帕蒂"),
            Map.entry("Paul", "保罗"),
            Map.entry("Payne", "佩恩"),
            Map.entry("Payton", "佩顿"),
            Map.entry("Pelle", "佩勒"),
            Map.entry("Peyton", "佩顿"),
            Map.entry("PJ", "P.J."),
            Map.entry("Pickett", "皮克特"),
            Map.entry("Pippen", "皮蓬"),
            Map.entry("Podziemski", "波杰姆斯基"),
            Map.entry("Pope", "波普"),
            Map.entry("Porter", "波特"),
            Map.entry("Portis", "波蒂斯"),
            Map.entry("Post", "波斯特"),
            Map.entry("Powell", "鲍威尔"),
            Map.entry("Precious", "普雷舍斯"),
            Map.entry("Prince", "普林斯"),
            Map.entry("Pritchard", "普理查德"),
            Map.entry("Porziņģis", "波尔津吉斯"),
            Map.entry("Queta", "克塔"),
            Map.entry("Quinten", "昆滕"),
            Map.entry("Randle", "兰德尔"),
            Map.entry("Reaves", "里夫斯"),
            Map.entry("Reed", "里德"),
            Map.entry("Reid", "里德"),
            Map.entry("Rob", "罗布"),
            Map.entry("Robinson", "罗宾逊"),
            Map.entry("Rollins", "罗林斯"),
            Map.entry("Ronald", "罗纳德"),
            Map.entry("Rui", "八村"),
            Map.entry("Rudy", "鲁迪"),
            Map.entry("Russell", "拉塞尔"),
            Map.entry("Ryan", "莱恩"),
            Map.entry("Sam", "萨姆"),
            Map.entry("Santi", "桑蒂"),
            Map.entry("Santos", "桑托斯"),
            Map.entry("Scheierman", "谢尔曼"),
            Map.entry("Schröder", "施罗德"),
            Map.entry("Scotty", "斯科蒂"),
            Map.entry("Sengun", "申京"),
            Map.entry("Shai", "谢伊"),
            Map.entry("Shake", "谢克"),
            Map.entry("Shamet", "沙梅特"),
            Map.entry("Shannon", "香农"),
            Map.entry("Sheppard", "谢泼德"),
            Map.entry("Siakam", "西亚卡姆"),
            Map.entry("Silva", "席尔瓦"),
            Map.entry("Simmons", "西蒙斯"),
            Map.entry("Sims", "西姆斯"),
            Map.entry("Smith", "史密斯"),
            Map.entry("Spencer", "斯宾塞"),
            Map.entry("Stephen", "斯蒂芬"),
            Map.entry("Steven", "史蒂文"),
            Map.entry("Stevens", "史蒂文斯"),
            Map.entry("Stewart", "斯图尔特"),
            Map.entry("Strawther", "斯特劳瑟"),
            Map.entry("Strus", "斯特鲁斯"),
            Map.entry("T.J", "T.J."),
            Map.entry("Tari", "塔里"),
            Map.entry("Tatum", "塔图姆"),
            Map.entry("Taurean", "托里恩"),
            Map.entry("Terrence", "特伦斯"),
            Map.entry("Thomas", "托马斯"),
            Map.entry("Thompson", "汤普森"),
            Map.entry("Tillman", "蒂尔曼"),
            Map.entry("Tim", "蒂姆"),
            Map.entry("Tobias", "托拜厄斯"),
            Map.entry("Tony", "托尼"),
            Map.entry("Toppin", "托平"),
            Map.entry("Torrey", "托里"),
            Map.entry("Towns", "唐斯"),
            Map.entry("Trace", "特雷斯"),
            Map.entry("Trayce", "特雷斯"),
            Map.entry("Trent", "特伦特"),
            Map.entry("Tristan", "特里斯坦"),
            Map.entry("Tucker", "塔克"),
            Map.entry("Turner", "特纳"),
            Map.entry("Ty", "泰"),
            Map.entry("Tyler", "泰勒"),
            Map.entry("Tyrese", "泰瑞斯"),
            Map.entry("Tyson", "泰森"),
            Map.entry("VanVleet", "范弗利特"),
            Map.entry("Vanderbilt", "范德比尔特"),
            Map.entry("Vincent", "文森特"),
            Map.entry("Vince", "文斯"),
            Map.entry("Vlatko", "弗拉特科"),
            Map.entry("Wade", "韦德"),
            Map.entry("Wagner", "瓦格纳"),
            Map.entry("Walker", "沃克"),
            Map.entry("Wallace", "华莱士"),
            Map.entry("Walsh", "沃尔什"),
            Map.entry("Ware", "韦尔"),
            Map.entry("Watson", "沃特森"),
            Map.entry("Wendell", "温德尔"),
            Map.entry("Westbrook", "威斯布鲁克"),
            Map.entry("White", "怀特"),
            Map.entry("Whitmore", "惠特莫尔"),
            Map.entry("Wiggins", "威金斯"),
            Map.entry("Williams", "威廉姆斯"),
            Map.entry("Wright", "赖特"),
            Map.entry("Xavier", "泽维尔"),
            Map.entry("Zach", "扎克"),
            Map.entry("Zeke", "齐克"),
            Map.entry("Zubac", "祖巴茨")
    );

    private static final Map<String, String> PLAYER_POSITION = Map.ofEntries(
            Map.entry("LeBron James", "SF"),
            Map.entry("Stephen Curry", "PG"),
            Map.entry("Kevin Durant", "PF"),
            Map.entry("Luka Doncic", "PG"),
            Map.entry("Luka Dončić", "PG"),
            Map.entry("Kyrie Irving", "SG"),
            Map.entry("Nikola Jokic", "C"),
            Map.entry("Nikola Jokić", "C"),
            Map.entry("Jayson Tatum", "SF"),
            Map.entry("Jaylen Brown", "SG"),
            Map.entry("Shai Gilgeous-Alexander", "PG"),
            Map.entry("Anthony Edwards", "SG"),
            Map.entry("Anthony Davis", "PF"),
            Map.entry("Jimmy Butler", "SF"),
            Map.entry("Jimmy Butler III", "SF"),
            Map.entry("Tyrese Haliburton", "PG"),
            Map.entry("Jalen Brunson", "PG"),
            Map.entry("Joel Embiid", "C"),
            Map.entry("Giannis Antetokounmpo", "PF"),
            Map.entry("Damian Lillard", "PG"),
            Map.entry("Donovan Mitchell", "SG"),
            Map.entry("Paolo Banchero", "PF"),
            Map.entry("Devin Booker", "SG"),
            Map.entry("James Harden", "PG"),
            Map.entry("Kawhi Leonard", "SF"),
            Map.entry("Paul George", "SF"),
            Map.entry("Chet Holmgren", "C"),
            Map.entry("Jalen Williams", "SF"),
            Map.entry("Alex Caruso", "SG"),
            Map.entry("Cason Wallace", "SG"),
            Map.entry("Luguentz Dort", "SF"),
            Map.entry("Isaiah Hartenstein", "C"),
            Map.entry("Aaron Wiggins", "SG"),
            Map.entry("Ajay Mitchell", "PG"),
            Map.entry("Bennedict Mathurin", "SG"),
            Map.entry("Pascal Siakam", "PF"),
            Map.entry("T.J. McConnell", "PG"),
            Map.entry("Andrew Nembhard", "SG"),
            Map.entry("Myles Turner", "C"),
            Map.entry("Aaron Nesmith", "SF"),
            Map.entry("Tony Bradley", "C")
    );

    public String teamDisplayName(String teamName) {
        if (teamName == null || teamName.isBlank()) {
            return "未知球队";
        }
        return TEAM_CN.getOrDefault(teamName, teamName);
    }

    public String teamAbbr(String teamName) {
        if (teamName == null || teamName.isBlank()) {
            return "TEAM";
        }
        return TEAM_ABBR.getOrDefault(teamName, fallbackAbbr(teamName));
    }

    public String playerDisplayName(String playerName) {
        if (playerName == null || playerName.isBlank()) {
            return "未知球员";
        }
        return PLAYER_CN.getOrDefault(playerName, translateNameParts(playerName));
    }

    public boolean hasPlayerChineseName(String playerName) {
        return playerName != null && !playerDisplayName(playerName).equals(playerName);
    }

    public String position(String rawPosition, String playerName) {
        if (rawPosition != null && !rawPosition.isBlank()) {
            return normalizePosition(rawPosition);
        }
        return PLAYER_POSITION.getOrDefault(playerName, fallbackPosition(playerName));
    }

    private String normalizePosition(String rawPosition) {
        String position = rawPosition.trim().toUpperCase();
        if (position.equals("PG") || position.equals("SG") || position.equals("SF")
                || position.equals("PF") || position.equals("C")) {
            return position;
        }
        return switch (position) {
            case "G" -> "SG";
            case "F" -> "SF";
            case "G-F", "F-G" -> "SF";
            case "F-C", "C-F" -> "PF";
            default -> fallbackPosition(position);
        };
    }

    private String fallbackPosition(String playerName) {
        if (playerName == null || playerName.isBlank()) {
            return "SG";
        }
        int index = Math.floorMod(playerName.hashCode(), FALLBACK_POSITIONS.length);
        return FALLBACK_POSITIONS[index];
    }

    private String translateNameParts(String playerName) {
        String normalized = playerName
                .replace(".", "")
                .replace(",", "")
                .replace(" III", "")
                .replace(" II", "")
                .replace(" Jr", "")
                .replace(" Jr.", "")
                .replace("-", " ");
        String[] parts = normalized.split("\\s+");
        StringBuilder translated = new StringBuilder();
        boolean hasTranslatedPart = false;
        for (String part : parts) {
            if (part.isBlank()) {
                continue;
            }
            String translatedPart = NAME_PART_CN.get(part);
            if (translatedPart == null) {
                translatedPart = part;
            } else {
                hasTranslatedPart = true;
            }
            if (!translated.isEmpty()) {
                translated.append("·");
            }
            translated.append(translatedPart);
        }
        return hasTranslatedPart ? translated.toString() : playerName;
    }

    private String fallbackAbbr(String teamName) {
        String[] words = teamName.split("\\s+");
        StringBuilder abbr = new StringBuilder();
        for (String word : words) {
            if (!word.isBlank()) {
                abbr.append(Character.toUpperCase(word.charAt(0)));
            }
            if (abbr.length() == 3) {
                break;
            }
        }
        return abbr.isEmpty() ? "TEAM" : abbr.toString();
    }
}
